export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
export const CLEAR_QUANTITIES = 'CLEAR_QUANTITIES'
export const APPLY_DISCOUNT = 'APPLY_DISCOUNT'
export const REMOVE_DISCOUNT = 'REMOVE_DISCOUNT'

export default {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  CHANGE_QUANTITY,
  CLEAR_QUANTITIES,
  APPLY_DISCOUNT,
  REMOVE_DISCOUNT
}
